######################################################################
# Automatically generated by qmake (2.01a) �ar Oca 21 18:31:34 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . qtc-gdbmacros resources src ui
INCLUDEPATH += . src

# Input
HEADERS += src/AnaPencere.h src/client.h src/tool.h
FORMS += ui/anapencere.ui
SOURCES += qtc-gdbmacros/gdbmacros.cpp \
           src/AnaPencere.cpp \
           src/client.cpp \
           src/main.cpp \
           src/tool.cpp
RESOURCES += resources/source.qrc
TRANSLATIONS += resources/olric_tr_TR.ts

DESTDIR = bin
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
RCC_DIR = build


QT           += xml
CONFIG += console

