######################################################################
# Automatically generated by qmake (2.01a) Cmt Eki 25 23:46:09 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . translations
INCLUDEPATH += .

# Input
HEADERS += AnaPencere.h client.h pencereclient.h
SOURCES += AnaPencere.cpp main.cpp pencereclient.cpp
RESOURCES += simgeler.qrc
TRANSLATIONS += translations/olric_eng.ts
